// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ProductDetailImpl _$$ProductDetailImplFromJson(Map<String, dynamic> json) =>
    _$ProductDetailImpl(
      code: json['code'] as String,
      kataban: json['kataban'] as String,
      name: json['name'] as String,
      bunrui: json['bunrui'] as String,
      kankyokbn: json['kankyokbn'] as String,
      zaikos: json['zaikos'] as int,
      zaikoz: json['zaikoz'] as int,
      zaikotens: (json['zaikotens'] as num).toDouble(),
      zaikotenz: (json['zaikotenz'] as num).toDouble(),
      kajozaikos: json['kajozaikos'] as int,
      kajozaikoz: json['kajozaikoz'] as int,
      jzans: json['jzans'] as int,
      jzanz: json['jzanz'] as int,
      hzans: json['hzans'] as int,
      hzanz: json['hzanz'] as int,
      usuryo1s: json['usuryo1s'] as int,
      usuryo1z: json['usuryo1z'] as int,
      usuryo2s: json['usuryo2s'] as int,
      usuryo2z: json['usuryo2z'] as int,
      usuryo3s: json['usuryo3s'] as int,
      usuryo3z: json['usuryo3z'] as int,
      usuryosums: json['usuryosums'] as int,
      usuryosumz: json['usuryosumz'] as int,
      usuryoavgs: json['usuryoavgs'] as int,
      usuryoavgz: json['usuryoavgz'] as int,
      ssuryo1s: json['ssuryo1s'] as int,
      ssuryo1z: json['ssuryo1z'] as int,
      ssuryo2s: json['ssuryo2s'] as int,
      ssuryo2z: json['ssuryo2z'] as int,
      ssuryo3s: json['ssuryo3s'] as int,
      ssuryo3z: json['ssuryo3z'] as int,
      ssuryosums: json['ssuryosums'] as int,
      ssuryosumz: json['ssuryosumz'] as int,
      ssuryoavgs: json['ssuryoavgs'] as int,
      ssuryoavgz: json['ssuryoavgz'] as int,
      nendo1: json['nendo1'] as int,
      nendo2: json['nendo2'] as int,
      nendo3: json['nendo3'] as int,
    );

Map<String, dynamic> _$$ProductDetailImplToJson(_$ProductDetailImpl instance) =>
    <String, dynamic>{
      'code': instance.code,
      'kataban': instance.kataban,
      'name': instance.name,
      'bunrui': instance.bunrui,
      'kankyokbn': instance.kankyokbn,
      'zaikos': instance.zaikos,
      'zaikoz': instance.zaikoz,
      'zaikotens': instance.zaikotens,
      'zaikotenz': instance.zaikotenz,
      'kajozaikos': instance.kajozaikos,
      'kajozaikoz': instance.kajozaikoz,
      'jzans': instance.jzans,
      'jzanz': instance.jzanz,
      'hzans': instance.hzans,
      'hzanz': instance.hzanz,
      'usuryo1s': instance.usuryo1s,
      'usuryo1z': instance.usuryo1z,
      'usuryo2s': instance.usuryo2s,
      'usuryo2z': instance.usuryo2z,
      'usuryo3s': instance.usuryo3s,
      'usuryo3z': instance.usuryo3z,
      'usuryosums': instance.usuryosums,
      'usuryosumz': instance.usuryosumz,
      'usuryoavgs': instance.usuryoavgs,
      'usuryoavgz': instance.usuryoavgz,
      'ssuryo1s': instance.ssuryo1s,
      'ssuryo1z': instance.ssuryo1z,
      'ssuryo2s': instance.ssuryo2s,
      'ssuryo2z': instance.ssuryo2z,
      'ssuryo3s': instance.ssuryo3s,
      'ssuryo3z': instance.ssuryo3z,
      'ssuryosums': instance.ssuryosums,
      'ssuryosumz': instance.ssuryosumz,
      'ssuryoavgs': instance.ssuryoavgs,
      'ssuryoavgz': instance.ssuryoavgz,
      'nendo1': instance.nendo1,
      'nendo2': instance.nendo2,
      'nendo3': instance.nendo3,
    };
